apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-tfdn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-tfdn
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-tfdn
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-tfdn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-tfdn
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-svqk-tenant/rhtap-demo-app/hacbs-test-project-tfdn@sha256:a3365c8fd33e44e04b7a9dfefcaedd194770803763b42752593fae5f5d06fe7c
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
